base_url = "___SITE_URL___"
title = "___SITE_TITLE___"

build_search_index = true
compile_sass = true
default_language = "en"
generate_feed = true
minify_html = true
render_emoji = true
taxonomies = []

[slugify]
paths = "off"

[search]
include_content = true
include_description = true
include_title = true

[markdown]
highlight_code = true

[extra]
home_graph = "___HOME_GRAPH___"
is_netlify = true
page_graph = "___PAGE_GRAPH___"
title_addition = "___SITE_TITLE_TAB___"

language_code = "en-US"
theme_color = "#fff"

ganalytics = "___GANALYTICS___"
timeformat = "%B %e, %Y"
timezone = "___TIMEZONE___"

